# version: '3'
# services:
#   # prisma:
#   #   image: prismagraphql/prisma:1.34
#   #   restart: always
#   #   ports:
#   #     - "4466:4466"
#   #   environment:
#   #     PRISMA_CONFIG: |
#   #       port: 4466
#   #       # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
#   #       # managementApiSecret: my-secret
#   #       databases:
#   #         default:
#   #           connector: mysql
#   #           host: mysql
#   #           user: root
#   #           password: prisma
#   #           rawAccess: true
#   #           port: 3306
#   #           migrations: true
#   #   links:
#   #     - mysql
#   mysql:
#     image: mysql:5.7
#     restart: always
#     # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Workbench
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: prisma
#     volumes:
#       - mysql:/var/lib/mysql
#   backend:
#     links:
#       - mysql
#       - prisma
#     depends_on:
#       - mysql
#       - prisma
#     container_name: backend
#     ports:
#       - '4000:4000'
#     stdin_open: true
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     build:
#       context: backend
#       dockerfile: Dockerfile
#     volumes:
#       - ./backend:/app
#       - /app/node_modules
#       - /app/prisma
#     command: bash ./deploy.sh
#   frontend:
#     container_name: frontend
#     ports:
#       - '3000:3000'
#     environment:
#       - CHOKIDAR_USEPOLLING=true
#     stdin_open: true
#     build:
#       context: frontend
#       dockerfile: Dockerfile
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
# volumes:
#   mysql:


version: '3.7'
services:
  mysql:
    container_name: mysql
    ports:
      - '3306:3306'
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: prisma
      MYSQL_ROOT_PASSWORD: primsa
    volumes:
      - mysql:/var/lib/mysql
  prisma:
    links:
      - mysql
    depends_on:
      - mysql
    container_name: prisma
    ports:
      - '5555:5555'
    build:
      context: backend/prisma
      dockerfile: Dockerfile
    volumes:
      - /app/prisma
  backend:
    links:
      - mysql
    depends_on:
      - mysql
    container_name: backend
    ports:
      - '4000:4000'
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /app/prisma
    stdin_open: true
    command: bash ./deploy.sh
  frontend:
    container_name: frontend
    ports:
      - '3000:3000'
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true

volumes:
  mysql: